// SPDX-License-Identifier: MIT
#ifndef __ELOS_CLIENTMANAGERSTART_UTEST_H__
#define __ELOS_CLIENTMANAGERSTART_UTEST_H__

#include <cmocka_extensions/cmocka_extensions.h>
#include <cmocka_extensions/mock_extensions.h>

#include "elos/clientmanager/clientmanager.h"

typedef struct {
    elosClientManagerContext_t *context;
    elosClientManagerParam_t *parameters;
} elosUteststateT_t;

void elosClientManagerStartUtestInitParameters(void **state);
void elosClientManagerStartUtestDeleteParameters(void **state);

TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartErrContextNull)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartErrParametersNull)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartErrBlacklistInitialize)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartExtErrInetPton)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartExtErrContextMutexInit)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartExtErrSemInit)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartExtErrConnectionMutexInitFirst)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartExtErrConnectionMutexInitMid)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartExtErrConnectionMutexInitLast)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartExtErrSocket)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartExtErrSetsockopt)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartExtErrBind)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartExtErrListen)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartExtErrPthreadCreate)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerStartSuccess)

#endif /* __ELOS_CLIENTMANAGERSTART_UTEST_H__ */
