// SPDX-License-Identifier: MIT
#pragma once

#include <safu/flags.h>

#define ELOS_EVENTDISPATCHER_FLAG_ACTIVE              SAFU_FLAG_CUSTOM_START_BIT
#define ELOS_EVENTDISPATCHER_FLAG_HAS_ACTIVE_BIT(__f) ((atomic_load(__f) & ELOS_EVENTDISPATCHER_FLAG_ACTIVE) != 0)

#ifndef ELOS_EVENTDISPATCHER_DEFAULT_VECTOR_SIZE
#define ELOS_EVENTDISPATCHER_DEFAULT_VECTOR_SIZE 8
#endif
