@startuml
skinparam linetype ortho
rectangle elos-tools as "elos-tools CI" {
  node Host as "Host" {
    component RobotContainer as "Robot Container"
    component ElosContainer as "Elos Container"
    package "Integration-Test" as IntegrationTest {
      artifact "test runner"
      artifact "tests" {
        rectangle tests [
          *.robot
          keywords.resources
          libraries
        ]
      }
    }
  }
  
  node Target as "Target" {
    component Elosd as "elosd"
  }
  
  rectangle Result as "Result" {
    artifact log as "log.html"
    artifact output as "output.xml"
    artifact report as "report.html"
  }
}

Host -[hidden]left-> Target
IntegrationTest .up.> RobotContainer : mount
RobotContainer -left-> ElosContainer : run test
ElosContainer ..> Target
Host -left-> Result
report -[hidden]right-> output
output -[hidden]right-> log
@enduml
