@startuml

participant Client
participant ClientManager
participant EventProcessor
collections EventFilter
queue EventQueue

group create a session
  Client --> ClientManager : connect()
  Client <-- ClientManager : Session
end

loop while client want's to publish
  group publish message for event
    Client --> EventProcessor : eventPublish("Event")
    EventProcessor --> EventFilter : filterEvent("Event")
    EventFilter --> EventQueue : appendEventWithMatch("Event")
    EventFilter --> EventFilter : dropEventWithNoMatch("Event")
    Client <-- EventProcessor : Result
  end
end

group close a session
  Client --> ClientManager : close()
  Client <-- ClientManager : Result
end
@enduml


