// SPDX-License-Identifier: MIT
#ifndef ELOS_EVENTFILTERNODEVECTORDELETEMEMBERS_UTEST_H
#define ELOS_EVENTFILTERNODEVECTORDELETEMEMBERS_UTEST_H

#include <cmocka_extensions/cmocka_extensions.h>

#include "eventprocessor/eventfilternodevector.h"

typedef struct elosTestState {
    elosEventFilterNodeVector_t efev;
} elosTestState_t;

TEST_CASE_FUNC_PROTOTYPES(elosTestEloEventFilterNodeVectorDeleteMembersNullParam)
TEST_CASE_FUNC_PROTOTYPES(elosTestEloEventFilterNodeVectorDeleteMembersNullData)
TEST_CASE_FUNC_PROTOTYPES(elosTestEloEventFilterNodeVectorDeleteMembersFreeFailed)
TEST_CASE_FUNC_PROTOTYPES(elosTestEloEventFilterNodeVectorDeleteMembersIterateFailed)
TEST_CASE_FUNC_PROTOTYPES(elosTestEloEventFilterNodeVectorDeleteMembersSuccess)

#endif /* ELOS_EVENTFILTERNODEVECTORDELETEMEMBERS_UTEST_H */
