// SPDX-License-Identifier: MIT
#pragma once

#ifndef ELOS_CONFIG_ROOT
#define ELOS_CONFIG_ROOT "/root/elos/"
#endif

#ifndef ELOS_CONFIG_CLIENTINPUTS
#define ELOS_CONFIG_CLIENTINPUTS ELOS_CONFIG_ROOT "ClientInputs/"
#endif

#ifndef ELOS_CONFIG_EVENTLOGGING
#define ELOS_CONFIG_EVENTLOGGING ELOS_CONFIG_ROOT "EventLogging/"
#endif

#ifndef ELOS_CONFIG_SCANNER
#define ELOS_CONFIG_SCANNER ELOS_CONFIG_ROOT "Scanner/"
#endif

#ifndef ELOS_CONFIG_STORAGEBACKEND
#define ELOS_CONFIG_STORAGEBACKEND ELOS_CONFIG_ROOT "StorageBackend/"
#endif
