// SPDX-License-Identifier: MIT
#ifndef SAMCONF_SIGNATURE_LOADER_GET_SIGNATURE_FOR_UTEST_H
#define SAMCONF_SIGNATURE_LOADER_GET_SIGNATURE_FOR_UTEST_H

#include <cmocka_extensions/cmocka_extensions.h>
#include <cmocka_extensions/mock_extensions.h>

TEST_CASE_FUNC_PROTOTYPES(samconfTestSamconfSignatureLoaderGetSignatureForSuccess)
TEST_CASE_FUNC_PROTOTYPES(samconfTestSamconfSignatureLoaderGetSignatureForAllocError)
TEST_CASE_FUNC_PROTOTYPES(samconfTestSamconfSignatureLoaderGetSignatureForAccessError)
TEST_CASE_FUNC_PROTOTYPES(samconfTestSamconfSignatureLoaderGetSignatureForReadError)

#endif /* SAMCONF_SIGNATURE_LOADER_GET_SIGNATURE_FOR_UTEST_H */
