// SPDX-License-Identifier: MIT
#pragma once

#ifndef ELOS_EVENTQUEUEMANAGER_DEFAULT_SIZE
#define ELOS_EVENTQUEUEMANAGER_DEFAULT_SIZE 64
#endif

#ifndef ELOS_EVENTQUEUE_DEFAULT_SIZE
#define ELOS_EVENTQUEUE_DEFAULT_SIZE 64
#endif

#ifndef ELOS_EVENTQUEUE_DEFAULT_LIMITEVENTS
#define ELOS_EVENTQUEUE_DEFAULT_LIMITEVENTS 0
#endif

#ifndef ELOS_EVENTQUEUE_DEFAULT_LIMITTIME_SEC
#define ELOS_EVENTQUEUE_DEFAULT_LIMITTIME_SEC 0
#endif

#ifndef ELOS_EVENTQUEUE_DEFAULT_LIMITTIME_NSEC
#define ELOS_EVENTQUEUE_DEFAULT_LIMITTIME_NSEC 0
#endif

#ifndef ELOS_EVENTFILTERNODEVECTOR_DEFAULT_SIZE
#define ELOS_EVENTFILTERNODEVECTOR_DEFAULT_SIZE 8
#endif
