// SPDX-License-Identifier: MIT
#ifndef __ELOS_CLIENTMANAGERTHREADGETFREECONNECTIONSLOT_UTEST_H__
#define __ELOS_CLIENTMANAGERTHREADGETFREECONNECTIONSLOT_UTEST_H__

#include <cmocka_mocks/mock_libc.h>

#include "elos/clientmanager/clientmanager.h"

// these must be the same values as in clientmanager_threads.c

#ifndef CONNECTION_SEMAPHORE_TIMEOUT_NSEC
#define CONNECTION_SEMAPHORE_TIMEOUT_NSEC (100 * 1000 * 1000)
#endif

#ifndef TIMESPEC_1SEC_IN_NSEC
#define TIMESPEC_1SEC_IN_NSEC 1000000000L
#endif

TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadGetFreeConnectionSlotExtErrClockGetTime)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadGetFreeConnectionSlotExtErrSemTimedwait)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadGetFreeConnectionSlotExtErrMutexLock)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadGetFreeConnectionSlotExtErrMutexUnlock01)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadGetFreeConnectionSlotExtErrMutexUnlock02)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadGetFreeConnectionSlotRecalcTvsec)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadGetFreeConnectionSlotEtimedout)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadGetFreeConnectionSlotEintr)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadGetFreeConnectionSlotThreadNotJoined)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadGetFreeConnectionSlotNoFreeConnection)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadGetFreeConnectionSlotSuccessFirst)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadGetFreeConnectionSlotSuccessMiddle)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadGetFreeConnectionSlotSuccessLast)

#endif /* __ELOS_CLIENTMANAGERTHREADGETFREECONNECTIONSLOT_UTEST_H__ */
