// SPDX-License-Identifier: MIT
#ifndef SAMCONF_CONFIG_BACKEND_NEW_UTEST_H
#define SAMCONF_CONFIG_BACKEND_MEW_UTEST_H

#include <cmocka_extensions/cmocka_extensions.h>

TEST_CASE_FUNC_PROTOTYPES(samconfTestSamconfConfigBackendNewSuccess)
TEST_CASE_FUNC_PROTOTYPES(samconfTestSamconfConfigBackendNewMemError)
TEST_CASE_FUNC_PROTOTYPES(samconfTestSamconfConfigBackendNewInitError)

#endif /* SAMCONF_CONFIG_BACKEND_NEW_UTEST_H */
