// SPDX-License-Identifier: MIT
#ifndef __ELOS_CLIENTMANAGERTHREADWAITFORINCOMINGCONNECTION_UTEST_H__
#define __ELOS_CLIENTMANAGERTHREADWAITFORINCOMINGCONNECTION_UTEST_H__

#include <cmocka_extensions/cmocka_extensions.h>
#include <cmocka_extensions/mock_extensions.h>

#include "cmocka_mocks/mock_libc.h"
#include "elos/clientmanager/clientmanager.h"
#include "mock_clientmanager.h"

TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadWaitForIncomingConnectionErrGetStatus)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadWaitForIncomingConnectionListenInactive)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadWaitForIncomingConnectionErrPselect)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadWaitForIncomingConnectionErrAccept)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadWaitForIncomingConnectionInterrupt)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadWaitForIncomingConnectionSuccessFdReady)
TEST_CASE_FUNC_PROTOTYPES(elosTestElosClientManagerThreadWaitForIncomingConnectionSuccessFdZero)

#endif /* __ELOS_CLIENTMANAGERTHREADWAITFORINCOMINGCONNECTION_UTEST_H__ */
