// SPDX-License-Identifier: MIT
#ifndef SAFU_JSON_ADD_OBJECT_H
#define SAFU_JSON_ADD_OBJECT_H

#include "json_utest.h"

TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddObjectArray)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddObjectObject)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddObjectErrArray)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddObjectErrObject)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddObjectErrNullKeyObject)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddObjectErrStringIndexArray)

#endif /* SAFU_JSON_ADD_OBJECT_H */
