// SPDX-License-Identifier: MIT
#ifndef SAFU_JSON_ADD_NEW_TIMESTAMP_H
#define SAFU_JSON_ADD_NEW_TIMESTAMP_H

#include "cmocka_mocks/mock_jsonc.h"
#include "json_utest.h"

TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampSuccessArray)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampSuccessObject)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampErrNewArrayArray)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampErrNewArrayObject)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampErrAddArrayArray)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampErrAddArrayObject)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampErrCreateSecArray)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampErrCreateSecObject)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampErrCreateNSecArray)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampErrCreateNSecObject)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampErrInsertSecArray)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampErrInsertSecObject)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampErrInsertNSecArray)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampErrInsertNSecObject)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampErrNoTimespecArray)
TEST_CASE_FUNC_PROTOTYPES(safuTestSafuJsonAddNewTimestampErrNoTimespecObject)

#endif /* SAFU_JSON_ADD_NEW_TIMESTAMP_H */
